# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: rsyslog-relp-echo-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: rsyslog-relp-echo-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: rsyslog-relp-echo-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  clusterIP: 10.2.64.54
  clusterIPs:
    - 10.2.64.54
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10250