# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.rsyslogConfig.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ required ".Values.rsyslogConfig.tls.ca is required" .Values.rsyslogConfig.tls.ca }}
  tls.crt: {{ required ".Values.rsyslogConfig.tls.crt is required" .Values.rsyslogConfig.tls.crt }}
  tls.key: {{ required ".Values.webhookConfig.tls.key is required" .Values.rsyslogConfig.tls.key }}
{{- end }}